### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by lucasBertola** [aspnet/Docs.fr-fr#10]
Hi
There is a missing link 
![image](https://user-images.githubusercontent.com/3074019/34417754-6a74ad80-ebfa-11e7-857d-a93cf6ac2cd3.png)

**Comment by lucasBertola** [comment]
You can find the link here [https://docs.microsoft.com/fr-fr/aspnet/core/index](url)

**Comment by nokura** [comment]
Hello @lucasBertola I cannot reproduce the issue. Since the folder structure has been changed, the TOC looks different now than what you pasted above. If I misunderstood your issue, please reactivate and let me know. Thank you so much for your input.
