### ISSUE TITLE
Introduction to ASP.NET Core SignalR: not localized in French

### ISSUE THREAD

**Issue by agriffard** [aspnet/Docs.fr-fr#150]
This url is not localized in French:
https://docs.microsoft.com/fr-fr/aspnet/core/signalr/introduction
while the other urls in the SignalR menu are correctly localized.

**Comment by agriffard** [comment]
Only get-started, dotnet-client and hubs are in French.

These ones are in English:
https://docs.microsoft.com/fr-fr/aspnet/core/signalr/javascript-client 
https://docs.microsoft.com/fr-fr/aspnet/core/signalr/publish-to-azure-web-app
https://docs.microsoft.com/fr-fr/aspnet/core/signalr/supported-platforms

Note: javascript-client.md is in the folder but not publish-to-azure-web-app and supported-platforms :
https://github.com/aspnet/Docs.fr-fr/tree/live/aspnetcore/signalr

**Comment by CeciAc** [comment]
Hello, @agriffard,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @agriffard, 
 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/aspnet/core/signalr/introduction. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
