### ISSUE TITLE
Missing code samples in Startup documentation

### ISSUE THREAD

**Issue by agriffard** [aspnet/Docs.fr-fr#154]
https://docs.microsoft.com/fr-fr/aspnet/core/fundamentals/startup?view=aspnetcore-2.1#setcompatibilityversion-for-aspnet-core-mvc

Some code samples are not displayed because there is no corresponding folder and file, compared to the en-us repository : https://github.com/aspnet/Docs/tree/live/aspnetcore/fundamentals/startup/sampleCompatibility 
Ex: [!code-csharp[Main](startup/sampleCompatibility/Startup.cs?name=snippet1)]

**Comment by CeciAc** [comment]
Hello, @agriffard,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @agriffard,

Thank you for your feedback. 
  
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX.  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
