### ISSUE TITLE
Left menu not displayed on French pages

### ISSUE THREAD

**Issue by agriffard** [aspnet/Docs.fr-fr#202]
The left menu does not appear on the fr-fr pages, only the version selector is displayed.

Ex: https://docs.microsoft.com/fr-fr/aspnet/core/?view=aspnetcore-2.2

**Comment by LisandroSu** [comment]
Hello, @agriffard 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @agriffard 

We started working on it yesterday and it should be working now. Can you double check?

Thanks!
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @agriffard 

The issue has been solved. Closing it.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team
