### ISSUE TITLE
Possible issue : Keyword 'page' is used internally by MVC's routing system

### ISSUE THREAD

**Issue by hybernatus** [aspnet/Docs.fr-fr#205]
Thank you for your great explanations on this topic.

Just a remark. I have had to change 'page' keyword into 'pageNumber' in order to make the code work. Otherwise the route is not determined properly.

You can rename 'page' to 'pageNumber' in the body of the method and in the ASP tag

(The keyword 'page' seems to be not only a reserved word in MVC'routing system but also in the context of a Razor view)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutoriel : Ajouter le tri, le filtrage et la pagination - ASP.NET MVC avec EF Core](https://docs.microsoft.com/fr-fr/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/aspnet/Docs.fr-fr/blob/live/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by hybernatus** [comment]
The term 'pageIndex' suits better to reality, these are not page numbers but indexes of group of pages. This is the term already used in PaginatedList CreateAsync definition

**Comment by CeciAc** [comment]
Hello, @hybernatus 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/Docs #11693](https://github.com/aspnet/Docs/issues/11693) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @hybernatus 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/Docs/issues/11693

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
