### ISSUE TITLE
Edit link not available

### ISSUE THREAD

**Issue by agriffard** [aspnet/Docs.fr-fr#213]
The Edit link is not displayed on this page:
https://docs.microsoft.com/fr-fr/aspnet/core/client-side/using-browserlink?view=aspnetcore-2.2
nor any of the pages below https://docs.microsoft.com/fr-fr/aspnet/core/client-side or https://docs.microsoft.com/fr-fr/aspnet/core/razor-components

**Comment by CeciAc** [comment]
Hello, @agriffard 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard 
can you please check this issue?
thanks!

**Comment by JasonCard** [comment]
Hi @agriffard,

Thank you for your feedback.
This is currently by-design as we have temporarily disabled Community Contribution (the Edit button) for contents that are machine translated. We have disabled the Edit button according to sub-folders, so this also includes index files, which is the only human translated file in the sub-folder. 
We hope to re-enable Community Contribution for machine translated content in the future. In the meantime, we would like to ask for your understanding and encourage contributions to our human translated content.

Kind regards,
Microsoft DOCS International Team
cc @CeciAc @SonjaSaltzman
